### PR TITLE
#18/eslint

### LINKED ISSUE #18: Inject linting into CI pipeline
# Overview

If I've got it right we don't have something like `pretest: npm review` in package.json to have linting as a part of test run.

# Tasks

- [ ] setup linting for travis
- [ ] make sure it passes

### PR DESCRIPTION
**Pull request by dumyan**
Resolves #18.

@roll please merge this so I can make the linting tests pass on the other branches merging into `update`.

Note: airbnb-config doesn't allow [dangling underscores](http://eslint.org/docs/rules/no-underscore-dangle). Whats your opinion, should I turn off this rule or rename the privates? I'm personally more in favor of turning off the rule.

### CODE REVIEW

**Comment by roll** [comment]
@dumyan 
feel free to turn off minor rules preventing normal work

**Comment by dumyan** [comment]
@roll please review. I have included eslint, eslint airbnb config and needed modules as development dependencies. Is there any particular reason why we rely on globals like these in the other javascript setups?

**Comment by roll** [comment]
> Is there any particular reason why we rely on globals like these in the other javascript setups?

could you please expand the question?

**Comment by dumyan** [comment]
eslint and related config and plugins are not listed as dependencies in jsontableschema-js. Nothing much significant, but I wondered why they are left out of the development dependencies list?

**Comment by roll** [comment]
I have no idea. And not sure how it workds at all (on CI) without it. Please PR jts if you'll be having time for it.

**Comment by dumyan** [comment]
It doesn't work. Liniting isn't run on Travis for jsontableschema-js and also the linting fails. I will fix this in some spare time.

**Pull request merged**
